version: "2"
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    ports:
      - "8020:80"
    user: "${UID}:${GID}"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:lts
    restart: always
    environment:
      MYSQL_DATABASE: yii2basic
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test:
        ["CMD", "mysql", "-uroot", "-ppassword", "--execute", "SHOW SCHEMAS;"]
      interval: 3s
      retries: 5
      timeout: 5s
volumes:
  db-data:
